# 린터/포맷터 친화적인 마크다운린트 구성(모든 서식 지정 규칙 비활성화)
default: true
blank_lines: false
bullet: false
html: false
indentation: false
line_length: false
spaces: false
url: false
whitespace: false

# MD024/no-duplicate-heading: 동일한 콘텐츠를 가진 여러 개의 헤더
MD024: false
# MD025/single-title: 동일한 문서에 여러 개의 최상위 제목
MD025: false
# MD026/no-trailing-punctuation: 헤더 끝에 문장부호를 사용하지 않기
MD026: false
# MD046/code-block-style: 코드 블록 스타일 [fenced or indented 통일]
MD046: false
