/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 사이드바는 파일 시스템에서 생성하거나 여기에서 명시적으로 정의할 수 있습니다.

 원하는 만큼 사이드바를 만들 수 있습니다.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 기본적으로 Docusaurus는 문서 폴더 구조에서 사이드바를 생성합니다.
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // 하지만 사이드바를 수동으로 만들 수도 있습니다.
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
